### ISSUE TITLE
error when uploading

### ISSUE THREAD

**Issue by angryjoeisme** [tobozo/esp8266_deauther_serial#2]
Arduino: 1.8.7 (Windows Store 1.8.15.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 9600"

Build options changed, rebuilding all
Sketch uses 532124 bytes (50%) of program storage space. Maximum is 1044464 bytes.
Global variables use 37980 bytes (46%) of dynamic memory, leaving 43940 bytes for local variables. Maximum is 81920 bytes.
Uploading 536272 bytes from C:\Users\{censored}\AppDatal/local\Temp\arduino_build_711090/esp8266_deauther_serial_this_one__.ino.bin to flash at 0x00000000
................................................................................ [ 15% ]
................................................................................ [ 30% ]
................................................................................ [ 45% ]
.....................An error occurred while uploading the sketch

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

this is the error message I am receiving when uploading your software to the hardware, 
any idea what I'm doing wrong??

**Comment by tobozo** [comment]
looks like a cable or ESP module problem, more related to the environment than to this project
have you tried different baud rates ? flashing at 9600 is really slow :-)

Anyway I'll archive this project since it won't be maintained anymore, also the serial communication is now implemented in the [parent project](https://github.com/spacehuhn/esp8266_deauther).

Please note this will also disable the comment system and you won't be able to reply here.

You can still get help on the ESP8266 by asking on the relevant [gitter](https://gitter.im/esp8266/Arduino), get hints on the deauther by participating or posting [issues](https://github.com/spacehuhn/esp8266_deauther/issues) or discuss it on spacehuhn's [Intergalactic ChickenCoop](https://discord.gg/p7gQfzV)
